from PyQt5 import QtWidgets
import sys
import sqlite3
from db_ui_tasks import Ui_MainWindow

app = QtWidgets.QApplication(sys.argv)

MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()

try:
    connection = sqlite3.connect('hl.db')        
    print('Successfully connected')
    print('#' * 20)
    
except Exception as ex:
    print('Connection refused')
    print(ex)
   
def save():
    try:        
        cursor = connection.cursor()
        
        # Удаляем все данные из таблицы
        cursor.execute("DELETE FROM hero") 
        cursor.execute("DELETE FROM task") 
        cursor.execute("DELETE FROM talent")               
        cursor.execute("DELETE FROM role")                      
        connection.commit()
        print('Table cleared successfully')
         
        # заполняем таблицы БД введенными данными. Пустые поля игнорируются
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_2.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_3.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_4.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_5.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_6.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_7.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_8.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_9.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_10.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_11.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_12.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_13.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_14.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_15.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_16.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_17.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.lineEdit_18.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_19.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_20.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_21.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_22.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_23.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_24.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_25.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_26.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_27.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_28.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_29.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_30.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_31.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_32.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_33.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_34.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_35.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.lineEdit_36.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_37.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_38.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_39.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_40.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_41.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_42.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_43.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_44.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_45.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_46.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_47.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_48.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_49.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_50.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_51.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_52.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_53.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.lineEdit_54.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_55.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_56.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_57.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_58.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_59.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_60.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_61.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_62.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_63.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_64.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_65.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_66.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_67.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_68.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_69.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_70.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_71.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.lineEdit_72.displayText()}')")
        connection.commit() 
        print('Data inserted successfully')
        
    finally:
       connection.close()
       exit()     
    
def clear_all():
    # очищаем все поля
    ui.lineEdit.clear()
    ui.lineEdit_2.clear()
    ui.lineEdit_3.clear()
    ui.lineEdit_4.clear()
    ui.lineEdit_5.clear()
    ui.lineEdit_6.clear()
    ui.lineEdit_7.clear()
    ui.lineEdit_8.clear()
    ui.lineEdit_9.clear()
    ui.lineEdit_10.clear()
    ui.lineEdit_11.clear()
    ui.lineEdit_12.clear()
    ui.lineEdit_13.clear()
    ui.lineEdit_14.clear()
    ui.lineEdit_15.clear()
    ui.lineEdit_16.clear()
    ui.lineEdit_17.clear()
    ui.lineEdit_18.clear()
    ui.lineEdit_19.clear()
    ui.lineEdit_20.clear()
    ui.lineEdit_21.clear()
    ui.lineEdit_22.clear()
    ui.lineEdit_23.clear()
    ui.lineEdit_24.clear()
    ui.lineEdit_25.clear()
    ui.lineEdit_26.clear()
    ui.lineEdit_27.clear()
    ui.lineEdit_28.clear()
    ui.lineEdit_29.clear()
    ui.lineEdit_30.clear()
    ui.lineEdit_31.clear()
    ui.lineEdit_32.clear()
    ui.lineEdit_33.clear()
    ui.lineEdit_34.clear()
    ui.lineEdit_35.clear()
    ui.lineEdit_36.clear()
    ui.lineEdit_37.clear()
    ui.lineEdit_38.clear()
    ui.lineEdit_39.clear()
    ui.lineEdit_40.clear()
    ui.lineEdit_41.clear()
    ui.lineEdit_42.clear()
    ui.lineEdit_43.clear()
    ui.lineEdit_44.clear()
    ui.lineEdit_45.clear()
    ui.lineEdit_46.clear()
    ui.lineEdit_47.clear()
    ui.lineEdit_48.clear()
    ui.lineEdit_49.clear()
    ui.lineEdit_50.clear()
    ui.lineEdit_51.clear()
    ui.lineEdit_52.clear()
    ui.lineEdit_53.clear()
    ui.lineEdit_54.clear()
    ui.lineEdit_55.clear()
    ui.lineEdit_56.clear()
    ui.lineEdit_57.clear()
    ui.lineEdit_58.clear()
    ui.lineEdit_59.clear()
    ui.lineEdit_60.clear()
    ui.lineEdit_61.clear()
    ui.lineEdit_62.clear()
    ui.lineEdit_63.clear()
    ui.lineEdit_64.clear()
    ui.lineEdit_65.clear()
    ui.lineEdit_66.clear()
    ui.lineEdit_67.clear()
    ui.lineEdit_68.clear()
    ui.lineEdit_69.clear()
    ui.lineEdit_70.clear()
    ui.lineEdit_71.clear()
    ui.lineEdit_72.clear()         
      
ui.pushButton.clicked.connect(save) # сохраняем данные в БД по нажатию кнопки 
ui.pushButton_2.clicked.connect(clear_all) # очищаем все поля

sys.exit(app.exec_())
