from PyQt5 import QtWidgets
import sys
import sqlite3
from DatabaseUI import Ui_MainWindow


# start Qt widget
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()


connection = sqlite3.connect('db.sqlite3')        
cursor = connection.cursor()

cursor.execute("SELECT name FROM `hero`")
heroes_tuple_list = cursor.fetchall()  # create list of tuples. 
heroes_list = []
for i in heroes_tuple_list:
    hero = ''.join(i) 
    heroes_list.append(hero)  # add a hero to the list.       


# filling in fields data from database 
if len(heroes_list) > 0:
    ui.hero1_lineedit.setText(f'{heroes_list[0]}')
    ui.hero2_lineedit.setText(f'{heroes_list[1]}')
    ui.hero3_lineedit.setText(f'{heroes_list[2]}')  
    ui.hero4_lineedit.setText(f'{heroes_list[3]}')
    ui.hero5_lineedit.setText(f'{heroes_list[4]}')
    ui.hero6_lineedit.setText(f'{heroes_list[5]}')
    ui.hero7_lineedit.setText(f'{heroes_list[6]}')
    ui.hero8_lineedit.setText(f'{heroes_list[7]}')
    ui.hero9_lineedit.setText(f'{heroes_list[8]}')  
    ui.hero10_lineedit.setText(f'{heroes_list[9]}')
    ui.hero11_lineedit.setText(f'{heroes_list[10]}')
    ui.hero12_lineedit.setText(f'{heroes_list[11]}')
    ui.hero13_lineedit.setText(f'{heroes_list[12]}')
    ui.hero14_lineedit.setText(f'{heroes_list[13]}')
    ui.hero15_lineedit.setText(f'{heroes_list[14]}')
    ui.hero16_lineedit.setText(f'{heroes_list[15]}')
    ui.hero17_lineedit.setText(f'{heroes_list[16]}')
    ui.hero18_lineedit.setText(f'{heroes_list[17]}')
    ui.hero19_lineedit.setText(f'{heroes_list[18]}')
    ui.hero20_lineedit.setText(f'{heroes_list[19]}')
    ui.hero21_lineedit.setText(f'{heroes_list[20]}')
    

cursor.execute("SELECT task FROM `task`")
task_tuple_list = cursor.fetchall()  # create list of tuples. 
tasks_list = []
for i in task_tuple_list:
    task = ''.join(i)  
    tasks_list.append(task)   # add a task to the list.  
        
# filling in fields data from database 
if len(tasks_list) > 0:
    ui.task1_lineedit.setText(f'{tasks_list[0]}')  
    ui.task2_lineedit.setText(f'{tasks_list[1]}')  
    ui.task3_lineedit.setText(f'{tasks_list[2]}')  
    ui.task4_lineedit.setText(f'{tasks_list[3]}')  
    ui.task5_lineedit.setText(f'{tasks_list[4]}')  
    ui.task6_lineedit.setText(f'{tasks_list[5]}')  
    ui.task7_lineedit.setText(f'{tasks_list[6]}')  
    ui.task8_lineedit.setText(f'{tasks_list[7]}')  
    ui.task9_lineedit.setText(f'{tasks_list[8]}')  
    ui.task10_lineedit.setText(f'{tasks_list[9]}')  
    ui.task11_lineedit.setText(f'{tasks_list[10]}')      
    ui.task12_lineedit.setText(f'{tasks_list[11]}')  
    ui.task13_lineedit.setText(f'{tasks_list[12]}')  
    ui.task14_lineedit.setText(f'{tasks_list[13]}')  
    ui.task15_lineedit.setText(f'{tasks_list[14]}')  
    ui.task16_lineedit.setText(f'{tasks_list[15]}')  
    ui.task17_lineedit.setText(f'{tasks_list[16]}')  
    ui.task18_lineedit.setText(f'{tasks_list[17]}')  
    ui.task19_lineedit.setText(f'{tasks_list[18]}')  
    ui.task20_lineedit.setText(f'{tasks_list[19]}')  
    ui.task21_lineedit.setText(f'{tasks_list[20]}')  

cursor.execute("SELECT talent FROM `talent`")
talents_tuple_list = cursor.fetchall()  # create list of tuples. 
talents_list = []
for i in talents_tuple_list:
    talent = ''.join(i)
    talents_list.append(talent)  # add a talent to the list.
        
# filling in fields data from database 
if len(talents_list) > 0:
    ui.talent1_lineedit.setText(f'{talents_list[0]}')
    ui.talent2_lineedit.setText(f'{talents_list[1]}')
    ui.talent3_lineedit.setText(f'{talents_list[2]}')
    ui.talent4_lineedit.setText(f'{talents_list[3]}')
    ui.talent5_lineedit.setText(f'{talents_list[4]}')
    ui.talent6_lineedit.setText(f'{talents_list[5]}')
    ui.talent7_lineedit.setText(f'{talents_list[6]}')
    ui.talent8_lineedit.setText(f'{talents_list[7]}')
    ui.talent9_lineedit.setText(f'{talents_list[8]}')
    ui.talent10_lineedit.setText(f'{talents_list[9]}')
    ui.talent11_lineedit.setText(f'{talents_list[10]}')
    ui.talent12_lineedit.setText(f'{talents_list[11]}')
    ui.talent13_lineedit.setText(f'{talents_list[12]}')
    ui.talent14_lineedit.setText(f'{talents_list[13]}')
    ui.talent15_lineedit.setText(f'{talents_list[14]}')
    ui.talent16_lineedit.setText(f'{talents_list[15]}')
    ui.talent17_lineedit.setText(f'{talents_list[16]}')
    ui.talent18_lineedit.setText(f'{talents_list[17]}')
    ui.talent19_lineedit.setText(f'{talents_list[18]}')
    ui.talent20_lineedit.setText(f'{talents_list[19]}')
    ui.talent21_lineedit.setText(f'{talents_list[20]}')
    

cursor.execute("SELECT role FROM `role`")
roles_tuple_list = cursor.fetchall()  # create list of tuples. 
roles_list = []    
for i in roles_tuple_list:
    role = ''.join(i)
    roles_list.append(role)  # add a role to the list.
  
if len(roles_list) > 0:
    ui.role1_lineedit.setText(f'{roles_list[0]}')
    ui.role2_lineedit.setText(f'{roles_list[1]}')
    ui.role3_lineedit.setText(f'{roles_list[2]}')
    ui.role4_lineedit.setText(f'{roles_list[3]}')
    ui.role5_lineedit.setText(f'{roles_list[4]}')
    ui.role6_lineedit.setText(f'{roles_list[5]}')
    ui.role7_lineedit.setText(f'{roles_list[6]}')
    ui.role8_lineedit.setText(f'{roles_list[7]}')
    ui.role9_lineedit.setText(f'{roles_list[8]}')
    ui.role10_lineedit.setText(f'{roles_list[9]}')
    ui.role11_lineedit.setText(f'{roles_list[10]}')
    ui.role12_lineedit.setText(f'{roles_list[11]}')
    ui.role13_lineedit.setText(f'{roles_list[12]}')
    ui.role14_lineedit.setText(f'{roles_list[13]}')
    ui.role15_lineedit.setText(f'{roles_list[14]}')
    ui.role16_lineedit.setText(f'{roles_list[15]}')
    ui.role17_lineedit.setText(f'{roles_list[16]}')
    ui.role18_lineedit.setText(f'{roles_list[17]}')
    ui.role19_lineedit.setText(f'{roles_list[18]}')
    ui.role20_lineedit.setText(f'{roles_list[19]}')
    ui.role21_lineedit.setText(f'{roles_list[20]}')

       
def save():
    # save data to the database
    try:
        connection = sqlite3.connect('db.sqlite3')        
        cursor = connection.cursor()
        
        # delete all data from the database before saving
        cursor.execute("DELETE FROM hero") 
        cursor.execute("DELETE FROM task") 
        cursor.execute("DELETE FROM talent")               
        cursor.execute("DELETE FROM role")                      
        connection.commit()
    
            
        # insert data into the database
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero1_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero2_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero3_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero4_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero5_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero6_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero7_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero8_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero9_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero10_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero11_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero12_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero13_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero14_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero15_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero16_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero17_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero18_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero19_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero20_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO hero (name) VALUES ('{ui.hero21_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task1_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task2_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task3_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task4_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task5_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task6_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task7_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task8_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task9_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task10_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task11_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task12_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task13_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task14_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task15_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task16_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task17_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task18_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task19_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task20_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO task (task) VALUES ('{ui.task21_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent1_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent2_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent3_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent4_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent5_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent6_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent7_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent8_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent9_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent10_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent11_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent12_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent13_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent14_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent15_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent16_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent17_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent18_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent19_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent20_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO talent (talent) VALUES ('{ui.talent21_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role1_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role2_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role3_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role4_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role5_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role6_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role7_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role8_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role9_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role10_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role11_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role12_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role13_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role14_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role15_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role16_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role17_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role18_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role19_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role20_lineedit.displayText()}')")
        cursor.execute(f"INSERT INTO role (role) VALUES ('{ui.role21_lineedit.displayText()}')")
        
        connection.commit()  
        
    finally:
        connection.close()
        exit()
            
    
def clear_all():
    # clear all fields
    ui.hero1_lineedit.clear()
    ui.hero2_lineedit.clear()
    ui.hero3_lineedit.clear()
    ui.hero4_lineedit.clear()
    ui.hero5_lineedit.clear()
    ui.hero6_lineedit.clear()
    ui.hero7_lineedit.clear()
    ui.hero8_lineedit.clear()
    ui.hero9_lineedit.clear()
    ui.hero10_lineedit.clear()
    ui.hero11_lineedit.clear()
    ui.hero12_lineedit.clear()
    ui.hero13_lineedit.clear()
    ui.hero14_lineedit.clear()
    ui.hero15_lineedit.clear()
    ui.hero16_lineedit.clear()
    ui.hero17_lineedit.clear()
    ui.hero18_lineedit.clear()
    ui.hero19_lineedit.clear()
    ui.hero20_lineedit.clear()
    ui.hero21_lineedit.clear()
    ui.task1_lineedit.clear()
    ui.task2_lineedit.clear()
    ui.task3_lineedit.clear()
    ui.task4_lineedit.clear()
    ui.task5_lineedit.clear()
    ui.task6_lineedit.clear()
    ui.task7_lineedit.clear()
    ui.task8_lineedit.clear()
    ui.task9_lineedit.clear()
    ui.task10_lineedit.clear()
    ui.task11_lineedit.clear()
    ui.task12_lineedit.clear()
    ui.task13_lineedit.clear()
    ui.task14_lineedit.clear()
    ui.task15_lineedit.clear()
    ui.task16_lineedit.clear()
    ui.task17_lineedit.clear()
    ui.task18_lineedit.clear()
    ui.task19_lineedit.clear()
    ui.task20_lineedit.clear()
    ui.task21_lineedit.clear()
    ui.talent1_lineedit.clear()
    ui.talent2_lineedit.clear()
    ui.talent3_lineedit.clear()
    ui.talent4_lineedit.clear()
    ui.talent5_lineedit.clear()
    ui.talent6_lineedit.clear()
    ui.talent7_lineedit.clear()
    ui.talent8_lineedit.clear()
    ui.talent9_lineedit.clear()
    ui.talent10_lineedit.clear()
    ui.talent11_lineedit.clear()
    ui.talent12_lineedit.clear()
    ui.talent13_lineedit.clear()
    ui.talent14_lineedit.clear()
    ui.talent15_lineedit.clear()
    ui.talent16_lineedit.clear()
    ui.talent17_lineedit.clear()
    ui.talent18_lineedit.clear()
    ui.talent19_lineedit.clear()
    ui.talent20_lineedit.clear()
    ui.talent21_lineedit.clear()
    ui.role1_lineedit.clear()    
    ui.role2_lineedit.clear()
    ui.role3_lineedit.clear()
    ui.role4_lineedit.clear()
    ui.role5_lineedit.clear()
    ui.role6_lineedit.clear()
    ui.role7_lineedit.clear()
    ui.role8_lineedit.clear()
    ui.role9_lineedit.clear()
    ui.role9_lineedit.clear()
    ui.role10_lineedit.clear()
    ui.role11_lineedit.clear()
    ui.role12_lineedit.clear()
    ui.role13_lineedit.clear()
    ui.role14_lineedit.clear()
    ui.role15_lineedit.clear()
    ui.role16_lineedit.clear()
    ui.role17_lineedit.clear()
    ui.role18_lineedit.clear()
    ui.role19_lineedit.clear()
    ui.role20_lineedit.clear()
    ui.role21_lineedit.clear()
            
      
ui.save_button.clicked.connect(save) 
ui.clear_button.clicked.connect(clear_all) 

sys.exit(app.exec_())
